spring.application.name=firstProject4TWIN6
spring.datasource.url=jdbc:mysql://localhost:3306/CafeDataBase\
?createDatabaseIfNotExist=true\
&useUnicode=true\
&useJDBCCompliantTimezoneShift=true\
&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
server.port=8088
server.servlet.context-path=/cafe
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



# --- Swagger UI Tweaks ---
# Enable search box in Swagger UI
springdoc.swagger-ui.filter=true

# Group operations by HTTP method
springdoc.swagger-ui.operationsSorter=method

# Sort tags alphabetically
springdoc.swagger-ui.tagsSorter=alpha





